# Generated by Django 5.0.4 on 2024-05-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfood4u', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
