# Generated by Django 5.0.4 on 2024-05-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfood4u', '0004_myimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='category',
        ),
    ]
